### ISSUE TITLE
unable to resolve compose-permission-handler

### ISSUE THREAD

**Issue by ticmaisdev** [dawidraszka/compose-permission-handler#17]
I'm unable to sync and use your package.
There's nothing wrong with my build files, I am able to use other packages from jitpack.io...

I've tried using 1.6.0-beta and 1.5.0, but none of them will be resolved.

Can you check your jitpack logs?

**Comment by ticmaisdev** [comment]
OK, I just found out that these versions are failing. Previous versions are fine:

![image](https://github.com/dawidraszka/compose-permission-handler/assets/128381407/64771142-491a-4984-8f7c-f1f6f3cc6dca)

**Comment by dawidraszka** [comment]
Thank you for bringing it up, I didn't check whether the version actually built after updating, I'm sorry. I'll check what's going on soon and rebuild these versions!

**Comment by dawidraszka** [comment]
I'm sorry it took so long, but it should be all fixed now :)

**Comment by ticmaisdev** [comment]
you're awesome @dawidraszka
